CppGauss: CppGauss.cc saps.cc saps.hh *.inc
	g++ -lm CppGauss.cc -L/home/gilbert/ICT-NewCLib/build/libitpp/lib -litpp -I/home/gilbert/ICT-NewCLib/build/libitpp/include -I../Collect/CppHelperFilesystemITPP/ -o CppGauss
