gauss: gauss.cc saps.cc saps.hh *.inc
	g++ -lm gauss.cc -L/home/gilbert/ICT-NewCLib/build/libitpp/lib -litpp -I/home/gilbert/ICT-NewCLib/build/libitpp/include -I../Collect/CppHelperFilesystemITPP/ -o gauss
